// quizQuestionsAI.js
// This file contains the complete quiz data generated by AI.
// French placeholders provided for the first 10 questions; others use an empty string for French.

const allQuizDataAI = [
  // AI-Generated Questions (Q1–Q100)
  {
    qNum: 1,
    text: {
      fr: "Non implémenté pour le français pour l'instant.",
      en: "Charisma can be enhanced by using metaphors, contrasts, and ambitious goals in speech."
    },
    answer: 'true'
  },
  {
    qNum: 2,
    text: {
      fr: "Non implémenté pour le français pour l'instant.",
      en: "Women consistently speak longer than men in leadership tasks regardless of context."
    },
    answer: 'false'
  },
  {
    qNum: 3,
    text: {
      fr: "Non implémenté pour le français pour l'instant.",
      en: "Leaders high in consideration behavior focus on building supportive relationships with subordinates."
    },
    answer: 'true'
  },
  {
    qNum: 4,
    text: {
      fr: "Non implémenté pour le français pour l'instant.",
      en: "Powerless speech is associated with perceptions of competence and persuasiveness."
    },
    answer: 'false'
  },
  {
    qNum: 5,
    text: {
      fr: "Non implémenté pour le français pour l'instant.",
      en: "Dehumanization can sometimes help individuals make difficult decisions more easily."
    },
    answer: 'true'
  },
  {
    qNum: 6,
    text: {
      fr: "Non implémenté pour le français pour l'instant.",
      en: "Women in leadership are often perceived through the lens of implicit bias and stereotype expectations."
    },
    answer: 'true'
  },
  {
    qNum: 7,
    text: {
      fr: "Non implémenté pour le français pour l'instant.",
      en: "The central route of persuasion is used when the listener is highly motivated and able to process information."
    },
    answer: 'true'
  },
  {
    qNum: 8,
    text: {
      fr: "Non implémenté pour le français pour l'instant.",
      en: "Mehrabian’s rule accurately states that 93% of communication is non-verbal."
    },
    answer: 'false'
  },
  {
    qNum: 9,
    text: {
      fr: "Non implémenté pour le français pour l'instant.",
      en: "Effective communication in multicultural teams requires low-context communication strategies."
    },
    answer: 'true'
  },
  {
    qNum: 10,
    text: {
      fr: "Non implémenté pour le français pour l'instant.",
      en: "Social proof is primarily based on conformity to what others are doing."
    },
    answer: 'true'
  },
  // Questions 11–100
  {
    qNum: 11,
    text: { fr: "", en: "Stereotype threat can reduce performance when individuals fear confirming negative stereotypes." },
    answer: 'true'
  },
  {
    qNum: 12,
    text: { fr: "", en: "In-group favoritism is unrelated to stereotype valence." },
    answer: 'false'
  },
  {
    qNum: 13,
    text: { fr: "", en: "Instrumental leadership includes strategic planning and facilitating subordinates' work." },
    answer: 'true'
  },
  {
    qNum: 14,
    text: { fr: "", en: "Transformational leadership is focused mainly on transactional exchanges like rewards and punishments." },
    answer: 'false'
  },
  {
    qNum: 15,
    text: { fr: "", en: "Implicit bias always occurs consciously." },
    answer: 'false'
  },
  {
    qNum: 16,
    text: { fr: "", en: "Structuring behavior involves defining roles and setting clear goals." },
    answer: 'true'
  },
  {
    qNum: 17,
    text: { fr: "", en: "Low-context cultures rely more on shared assumptions than explicit communication." },
    answer: 'false'
  },
  {
    qNum: 18,
    text: { fr: "", en: "According to the Elaboration Likelihood Model, the peripheral route involves high cognitive processing." },
    answer: 'false'
  },
  {
    qNum: 19,
    text: { fr: "", en: "Obedience is driven by the desire to be liked and accepted by others." },
    answer: 'false'
  },
  {
    qNum: 20,
    text: { fr: "", en: "Self-leadership involves setting personal goals and rewarding oneself." },
    answer: 'true'
  },
  {
    qNum: 21,
    text: { fr: "", en: "The transactional model of communication accounts for context, such as culture and relationships." },
    answer: 'true'
  },
  {
    qNum: 22,
    text: { fr: "", en: "High-context cultures rely mostly on explicit verbal messages." },
    answer: 'false'
  },
  {
    qNum: 23,
    text: { fr: "", en: "Low-context cultures value directness and clarity in communication." },
    answer: 'true'
  },
  {
    qNum: 24,
    text: { fr: "", en: "Non-verbal communication includes gestures, posture, and facial expressions." },
    answer: 'true'
  },
  {
    qNum: 25,
    text: { fr: "", en: "In leadership, power can only come from formal authority." },
    answer: 'false'
  },
  {
    qNum: 26,
    text: { fr: "", en: "Extraversion has the highest correlation with leadership effectiveness among the Big Five traits." },
    answer: 'true'
  },
  {
    qNum: 27,
    text: { fr: "", en: "Introverts can never be effective leaders, even when behaving extravertedly." },
    answer: 'false'
  },
  {
    qNum: 28,
    text: { fr: "", en: "The scientific method must be objective, empirical, and reproducible." },
    answer: 'true'
  },
  {
    qNum: 29,
    text: { fr: "", en: "Falsifiability means a theory must be impossible to disprove." },
    answer: 'false'
  },
  {
    qNum: 30,
    text: { fr: "", en: "Evidence-based management uses data and research to guide decisions." },
    answer: 'true'
  },
  {
    qNum: 31,
    text: { fr: "", en: "The Great Man Theory assumes leadership is developed through experience." },
    answer: 'false'
  },
  {
    qNum: 32,
    text: { fr: "", en: "Task-oriented leaders focus on relationships and team harmony." },
    answer: 'false'
  },
  {
    qNum: 33,
    text: { fr: "", en: "Consideration behavior involves concern for the well-being of team members." },
    answer: 'true'
  },
  {
    qNum: 34,
    text: { fr: "", en: "Contingency theories argue that one leadership style fits all situations." },
    answer: 'false'
  },
  {
    qNum: 35,
    text: { fr: "", en: "Fiedler’s model evaluates leader-member relations, task structure, and position power." },
    answer: 'true'
  },
  {
    qNum: 36,
    text: { fr: "", en: "Path-goal theory focuses on removing obstacles and motivating followers." },
    answer: 'true'
  },
  {
    qNum: 37,
    text: { fr: "", en: "LMX theory suggests leaders treat all team members equally by default." },
    answer: 'false'
  },
  {
    qNum: 38,
    text: { fr: "", en: "Participative leadership involves high relationship-orientation and low task-orientation." },
    answer: 'true'
  },
  {
    qNum: 39,
    text: { fr: "", en: "Transformational leaders often display idealized influence and inspirational motivation." },
    answer: 'true'
  },
  {
    qNum: 40,
    text: { fr: "", en: "Transactional leaders focus on inspiring vision and individual growth." },
    answer: 'false'
  },
  {
    qNum: 41,
    text: { fr: "", en: "Contingent reward is part of transformational leadership." },
    answer: 'false'
  },
  {
    qNum: 42,
    text: { fr: "", en: "Management-by-exception can be either active or passive." },
    answer: 'true'
  },
  {
    qNum: 43,
    text: { fr: "", en: "Laissez-faire leadership is characterized by high involvement and feedback." },
    answer: 'false'
  },
  {
    qNum: 44,
    text: { fr: "", en: "Instrumental leadership involves strategic planning and technical support." },
    answer: 'true'
  },
  {
    qNum: 45,
    text: { fr: "", en: "Objective performance criteria include things like revenue and sales data." },
    answer: 'true'
  },
  {
    qNum: 46,
    text: { fr: "", en: "Subjective performance criteria include peer ratings and supervisor evaluations." },
    answer: 'true'
  },
  {
    qNum: 47,
    text: { fr: "", en: "Interpersonal perception involves interpreting others’ behaviors and intentions." },
    answer: 'true'
  },
  {
    qNum: 48,
    text: { fr: "", en: "The halo effect is when one positive trait affects our overall impression." },
    answer: 'true'
  },
  {
    qNum: 49,
    text: { fr: "", en: "Powerful speech typically includes lots of hesitations and disclaimers." },
    answer: 'false'
  },
  {
    qNum: 50,
    text: { fr: "", en: "Perceived facial dominance is linked to perceptions of leadership ability." },
    answer: 'true'
  },
  {
    qNum: 51,
    text: { fr: "", en: "Emergent leadership refers to formal appointment to a leadership position." },
    answer: 'false'
  },
  {
    qNum: 52,
    text: { fr: "", en: "Expectation States Theory suggests that people’s expectations shape who becomes a leader." },
    answer: 'true'
  },
  {
    qNum: 53,
    text: { fr: "", en: "In-group members in LMX theory receive fewer opportunities than out-group members." },
    answer: 'false'
  },
  {
    qNum: 54,
    text: { fr: "", en: "Women are often stereotyped as more communal, while men are seen as more agentic." },
    answer: 'true'
  },
  {
    qNum: 55,
    text: { fr: "", en: "Implicit leadership theories are based on what people think a leader should look or act like." },
    answer: 'true'
  },
  {
    qNum: 56,
    text: { fr: "", en: "The backlash effect punishes people who go against stereotypical expectations." },
    answer: 'true'
  },
  {
    qNum: 57,
    text: { fr: "", en: "Social role theory links gender stereotypes to historical divisions of labor." },
    answer: 'true'
  },
  {
    qNum: 58,
    text: { fr: "", en: "The IAT test measures conscious opinions about social categories." },
    answer: 'false'
  },
  {
    qNum: 59,
    text: { fr: "", en: "Stereotype threat can hurt performance, especially in domains that matter to the individual." },
    answer: 'true'
  },
  {
    qNum: 60,
    text: { fr: "", en: "Perspective-taking can help reduce implicit bias." },
    answer: 'true'
  },
  {
    qNum: 61,
    text: { fr: "", en: "Code-switching helps facilitate cross-cultural communication." },
    answer: 'true'
  },
  {
    qNum
